image: node:6.3.0
 
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - node --version
          - npm --version
          - npm install -g angular-cli 
          - cd client
          - npm install
          - ng build
